#!/usr/bin/env python3
"""Regenerate the switch registry from the sources.

    tools/mkswitches.py            # rewrite src/damswitch_list.h and docs/SWITCHES.md
    tools/mkswitches.py --check    # exit 1 if either is out of date

Every CCX_* name the binary reads is found by scanning for getenv in the C
and Fortran sources.  The generated header is what damswitch.c reports from,
so a run's log states its own configuration and a misspelt switch is named
instead of silently doing nothing - which is the failure that makes an A/B
uninformative rather than wrong, and therefore the expensive kind.
"""
import argparse,os,re,sys,collections

ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC=os.path.join(ROOT,'src')
HDR=os.path.join(SRC,'damswitch_list.h')
DOC=os.path.join(ROOT,'docs','SWITCHES.md')
COV=os.path.join(ROOT,'test','regress','covered.txt')
GETENV=re.compile(r'getenv\s*\(\s*[\'"](CCX_[A-Z0-9_]+)[\'"]')

BANNER=re.compile(r'printf\s*\(\s*"((?:[^"\\\\]|\\\\.)*)"((?:\s*"(?:[^"\\\\]|\\\\.)*")*)')

def banner(txt,pos):
    """The banner this switch prints, taken verbatim from the source.

    Only a printf that appears BEFORE the next getenv of any CCX_ name is
    accepted, so a switch cannot borrow its neighbour's description - which
    is what a naive nearest-printf search does, and it produces confident
    nonsense.  A switch that shares a parse block with another therefore gets
    no description here, which is the honest answer."""
    nxt=GETENV.search(txt,pos)
    end=nxt.start() if nxt else min(len(txt),pos+2500)
    m=BANNER.search(txt,pos,end)
    if not m: return None
    s=m.group(1)+m.group(2)
    s=re.sub(r'"\s*"','',s)
    s=s.replace('\\n',' ').replace('\\"',"'")
    s=re.sub(r'%[-0-9.*]*(?:"\s*ITGFORMAT\s*"|[a-zA-Z])','<value>',s)
    s=s.replace('"','')
    s=re.sub(r'\s+',' ',s).strip()
    s=re.sub(r'(\s*<value>)+$','',s).strip()
    if s.startswith('*ERROR') or len(s)<30: return None
    return s

COMMENT=re.compile(r'/\*(.*?)\*/',re.S)

def preceding_comment(txt,pos):
    """The C comment block that ends just above this getenv, if it does.

    Falls back to this only when the switch prints no banner, and only when
    the comment is genuinely adjacent - at most two lines above - so a
    comment belonging to something else higher up is not attributed here."""
    line_start=txt.rfind('\n',0,pos)
    if line_start<0: return None
    head=txt[:line_start]
    best=None
    for m in COMMENT.finditer(head): best=m
    if best is None: return None
    between=head[best.end():]
    if between.count('\n')>2 or between.strip(): return None
    body=re.sub(r'^\s*\*+','',best.group(1),flags=re.M)
    body=re.sub(r'\s+',' ',body).strip()
    if len(body)<40: return None
    return body

def scan():
    where=collections.defaultdict(set); desc={}
    for dirpath,_,files in os.walk(SRC):
        for fn in sorted(files):
            if not fn.endswith(('.c','.f','.h')): continue
            if fn=='damswitch_list.h': continue
            txt=open(os.path.join(dirpath,fn),errors='replace').read()
            for m in GETENV.finditer(txt):
                where[m.group(1)].add(fn)
                if m.group(1) not in desc:
                    b=banner(txt,m.end())
                    if b is None and fn.endswith(('.c','.h')):
                        c=preceding_comment(txt,m.start())
                        if c: b='(from the comment above it) '+c
                    if b: desc[m.group(1)]=b
    return {k:sorted(v) for k,v in sorted(where.items())},desc

def docs_text():
    out=[]
    for dirpath,_,files in os.walk(ROOT):
        if '.git' in dirpath.split(os.sep): continue
        for fn in files:
            if fn.endswith('.md') and os.path.join(dirpath,fn)!=DOC:
                out.append(open(os.path.join(dirpath,fn),errors='replace').read())
    return '\n'.join(out)

def header(sw):
    L=["/* GENERATED by tools/mkswitches.py - do not edit.",
       "",
       "   Every CCX_* name this binary reads.  damswitch.c reports the ones",
       "   that are set and names anything else in the environment that looks",
       "   like one of ours, so a misspelt switch is caught on the spot rather",
       "   than quietly doing nothing.",
       "",
       "   Regenerate with tools/mkswitches.py; tools/mkswitches.py --check",
       "   fails if this file is stale. */",
       "",
       "#define DAMSWITCH_COUNT %d"%len(sw),
       "",
       "static const char *const damswitch_name[DAMSWITCH_COUNT]={"]
    for k in sw: L.append('  "%s",'%k)
    L+=["};",""]
    return "\n".join(L)

def coverage():
    """Switches that the three-minute gate actually puts in force.

    Recorded by test/regress/run.py --record-coverage from the [SWITCHES]
    banner of each case, so it is measured rather than declared."""
    if not os.path.exists(COV): return set()
    return {l.strip() for l in open(COV) if l.strip()}

def document(sw,dtxt,desc):
    cov=coverage()
    known=set(sw)
    nd=[k for k in sw if k not in dtxt and k not in desc]
    L=["# Environment switches",
       "",
       "GENERATED by `tools/mkswitches.py` - do not edit by hand.",
       "",
       "| | |",
       "|---|---|",
       "| names the binary reads | **%d** |"%len(sw),
       "| that print a banner of their own | %d |"%len([k for k in sw if k in desc]),
       "| mentioned in some other `.md` | %d |"%len([k for k in sw if k in dtxt]),
       "| **explained nowhere at all** | **%d** |"%len(nd),
       "| exercised by `test/regress/run.py` | %d |"%len([k for k in sw if k in cov]),
       "| **never set by any test in this tree** | **%d** |"%len([k for k in sw if k not in cov]),
       "",
       "Every run prints the ones that are set, and names anything in the",
       "environment starting with `CCX_` that is not in this list - see",
       "`[SWITCHES]` at the top of any `run.log`.",
       "",
       "The **what** column is taken verbatim from the source: the banner",
       "printed by the block that reads the switch, or failing that the",
       "comment immediately above the line that reads it.  Nothing here is",
       "written by hand or inferred, which is the point - and also the",
       "limit.  Several switches are parsed in a shared block with one",
       "banner between them, so what you see may describe the mechanism",
       "rather than that one knob.  A blank means the code says nothing",
       "there at all; guessing would have produced confident nonsense.",
       "",
       "| switch | read by | elsewhere | in the gate | what it says of itself |",
       "|---|---|---|---|---|"]
    for k in sw:
        L.append("| `%s` | %s | %s | %s | %s |"
                 %(k,", ".join("`%s`"%f for f in sw[k]),
                   "yes" if k in dtxt else "**no**",
                   "yes" if k in cov else "-",
                   desc.get(k,"").replace("|","\\|")))
    L+=["",
        "\"elsewhere\" means the name appears in some other markdown file in",
        "this tree.  It is a presence check, not a quality one.  A switch with",
        "neither a banner nor a mention elsewhere has nothing written about it",
        "anywhere except the line that reads it."]
    return "\n".join(L)+"\n"

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true')
    a=ap.parse_args()
    sw,desc=scan(); h=header(sw); d=document(sw,docs_text(),desc)
    if a.check:
        bad=[]
        for path,want in ((HDR,h),(DOC,d)):
            have=open(path).read() if os.path.exists(path) else None
            if have!=want: bad.append(path)
        if bad:
            print("stale, regenerate with tools/mkswitches.py:")
            for p in bad: print("  "+os.path.relpath(p,ROOT))
            return 1
        print("switch registry is up to date (%d switches)"%len(sw))
        return 0
    os.makedirs(os.path.dirname(DOC),exist_ok=True)
    open(HDR,'w').write(h); open(DOC,'w').write(d)
    print("wrote %s and %s: %d switches"%(os.path.relpath(HDR,ROOT),
                                          os.path.relpath(DOC,ROOT),len(sw)))
    return 0

if __name__=='__main__': sys.exit(main())
